"use client";
import { useEffect, useState } from "react";
import { cleanText, cloneResume, defaultSectionOrder, emptyResume, Resume, SectionId, sectionLabels } from "../lib/types";

type Props = { initial: Resume; resumes: Resume[]; user: string }; type Tab = "profile" | "education" | "experience" | "internships" | "projects" | "campus" | "awards" | "skills" | "custom" | "settings" | "order" | "import";
const tabs: [Tab, string][] = [["profile", "基本信息"], ["education", "教育经历"], ["experience", "工作经历"], ["internships", "实习经历"], ["projects", "项目经历"], ["campus", "校园经历"], ["awards", "奖项荣誉"], ["skills", "专业技能"], ["custom", "自定义模块"], ["settings", "排版设置"], ["order", "模块顺序"], ["import", "智能导入"]];
const themes = [{ id: "standard" as const, label: "简约", color: "#1976d2" }, { id: "product" as const, label: "产品", color: "#0f8a6a" }, { id: "technical" as const, label: "技术", color: "#5e5ce6" }];
const text = (v: unknown) => cleanText(v); const saveJson = (resume: Resume) => fetch("/api/resumes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(resume) });

export default function Workbench({ initial, resumes, user }: Props) {
  const [resume, setResume] = useState(initial); const [items, setItems] = useState(resumes); const [tab, setTab] = useState<Tab>("profile"); const [notice, setNotice] = useState(""); const [status, setStatus] = useState("已保存"); const [beforeImport, setBeforeImport] = useState<Resume | null>(null); const [raw, setRaw] = useState("");
  useEffect(() => { const timer = setTimeout(async () => { setStatus("保存中..."); try { const response = await saveJson(resume); const saved = await response.json(); if (!response.ok) throw new Error(saved.error); setResume(saved); setItems((all) => [saved, ...all.filter((item) => item.id !== saved.id)]); setStatus("已保存"); } catch { setStatus("保存失败，当前内容仍保留"); } }, 500); return () => clearTimeout(timer); }, [resume]);
  const update = (mutate: (draft: Resume) => void) => setResume((current) => { const draft = cloneResume(current); mutate(draft); return draft; });
  const create = () => { const next = emptyResume(); setResume(next); setItems((all) => [next, ...all]); setTab("profile"); setNotice("已创建新简历"); };
  const importText = async () => { try { const response = await fetch("/api/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: raw, resume }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setBeforeImport(cloneResume(resume)); setResume(data); setRaw(""); setTab("profile"); setNotice("导入完成，可点击导入前版本恢复"); } catch (e) { setNotice(e instanceof Error ? e.message : "导入失败"); } };
  const exportFile = async (format: "pdf" | "png" | "jpg") => { try { const response = await fetch("/api/export", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ format, resume }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || "导出失败"); } const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `${text(resume.profile.name) || "resume"}.${format}`; link.click(); URL.revokeObjectURL(url); } catch (e) { setNotice(e instanceof Error ? e.message : "导出失败"); } };
  const move = (index: number, direction: -1 | 1) => update((draft) => { const order = [...draft.sectionOrder]; const target = index + direction; if (target < 0 || target >= order.length) return; [order[index], order[target]] = [order[target], order[index]]; draft.sectionOrder = order; });
  return <main className="workbench"><header className="topbar"><div className="brand"><b>R</b><strong>简历工作台</strong><span>{user}</span></div><div className="top-actions"><span>{status}</span><button className="secondary" onClick={() => fetch("/api/auth", { method: "DELETE" }).then(() => location.reload())}>退出</button><button className="primary" onClick={() => exportFile("pdf")}>导出 PDF</button><button className="secondary" onClick={() => exportFile("png")}>PNG</button><button className="secondary" onClick={() => exportFile("jpg")}>JPG</button></div></header><div className="layout"><aside className="sidebar"><div className="side-title"><strong>我的简历</strong><button title="新建简历" onClick={create}>+</button></div><div className="resume-list">{items.map((item) => <button key={item.id} className={item.id === resume.id ? "resume selected" : "resume"} onClick={() => setResume(cloneResume(item))}><strong>{text(item.name) || "未命名简历"}</strong><span>{text(item.targetRole) || "未设置岗位"}</span></button>)}</div><div className="versions"><span>版本</span><button onClick={() => { setResume(cloneResume(resume)); setNotice("已恢复当前草稿"); }}>当前草稿</button><button disabled={!beforeImport} onClick={() => beforeImport && (setResume(cloneResume(beforeImport)), setNotice("已恢复导入前版本"))}>导入前版本</button></div><p>数据保存在 D:\简历<br />不会上传到云端</p></aside><section className="editor"><div className="editor-head"><div><input value={resume.name} onChange={(e) => update((d) => { d.name = e.target.value; })} /><p>{text(resume.targetRole) || "未设置目标岗位"}</p></div><div className="theme-list">{themes.map((theme) => <button key={theme.id} title={`切换${theme.label}模板`} className={resume.theme === theme.id ? "theme selected" : "theme"} style={{ background: theme.color }} onClick={() => update((d) => { d.theme = theme.id; })} />)}</div></div><nav className="tabs">{tabs.map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}<div className="form-panel"><Editor tab={tab} resume={resume} update={update} raw={raw} setRaw={setRaw} importText={importText} move={move} /></div></section><aside className="preview"><div className="preview-head"><span>A4 实时预览</span><span>{themes.find((t) => t.id === resume.theme)?.label}</span></div><Preview resume={resume} /></aside></div></main>;
}

function Editor({ tab, resume, update, raw, setRaw, importText, move }: { tab: Tab; resume: Resume; update: (fn: (d: Resume) => void) => void; raw: string; setRaw: (v: string) => void; importText: () => void; move: (i: number, d: -1 | 1) => void }) {
  if (tab === "profile") return <section><h1>基本信息</h1><div className="fields two">{([["name", "姓名"], ["headline", "个人标签"], ["phone", "手机"], ["email", "邮箱"], ["city", "城市"]] as const).map(([key, label]) => <label key={key}><span>{label}</span><input value={resume.profile[key]} onChange={(e) => update((d) => { d.profile[key] = e.target.value; })} /></label>)}</div><label><span>目标岗位</span><input value={resume.targetRole} onChange={(e) => update((d) => { d.targetRole = e.target.value; })} /></label><label><span>个人概述</span><textarea value={resume.summary} onChange={(e) => update((d) => { d.summary = e.target.value; })} /></label></section>;
  if (tab === "settings") return <section><h1>排版设置</h1><label><span>字体大小</span><select value={resume.fontSize} onChange={(e) => update((d) => { d.fontSize = e.target.value as Resume["fontSize"]; })}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label><span>段落间距</span><select value={resume.spacing} onChange={(e) => update((d) => { d.spacing = e.target.value as Resume["spacing"]; })}><option value="compact">紧凑</option><option value="normal">标准</option><option value="relaxed">宽松</option></select></label></section>;
  if (tab === "order") return <section><h1>模块顺序</h1><p>使用上移、下移调整右侧预览和导出顺序。</p>{resume.sectionOrder.map((id, index) => <div className="order-row" key={id}><strong>{sectionLabels[id]}</strong><span><button className="secondary" disabled={index === 0} onClick={() => move(index, -1)}>上移</button><button className="secondary" disabled={index === resume.sectionOrder.length - 1} onClick={() => move(index, 1)}>下移</button></span></div>)}</section>;
  if (tab === "import") return <section><h1>智能导入</h1><p>粘贴带有基本信息、教育经历、实习经历等关键词的简历文本。</p><textarea className="large" value={raw} onChange={(e) => setRaw(e.target.value)} /><button className="primary" disabled={!raw.trim()} onClick={importText}>识别并填充</button></section>;
  if (tab === "education") return <Education resume={resume} update={update} />;
  if (tab === "awards" || tab === "skills") return <Lines title={tab === "awards" ? "奖项荣誉" : "专业技能"} values={tab === "awards" ? resume.awards : resume.skills} update={(values) => update((d) => { if (tab === "awards") d.awards = values; else d.skills = values; })} />;
  if (tab === "custom") return <Custom resume={resume} update={update} />;
  const key = tab as "experience" | "internships" | "projects" | "campus"; return <Records title={sectionLabels[key]} kind={key} records={resume[key]} update={update} />;
}

function Education({ resume, update }: { resume: Resume; update: (fn: (d: Resume) => void) => void }) { const item = resume.education[0] || { school: "", degree: "", major: "", date: "", detail: "" }; return <section><h1>教育经历</h1><div className="fields two">{([["school", "学校"], ["major", "专业"], ["degree", "学历"], ["date", "时间"]] as const).map(([key, label]) => <label key={key}><span>{label}</span><input value={item[key]} onChange={(e) => update((d) => { if (!d.education.length) d.education.push({ ...item }); d.education[0][key] = e.target.value; })} /></label>)}</div><label><span>补充说明</span><textarea value={item.detail} onChange={(e) => update((d) => { if (!d.education.length) d.education.push({ ...item }); d.education[0].detail = e.target.value; })} /></label><button className="danger" onClick={() => update((d) => { d.education = []; })}>删除教育经历</button></section>; }
function Records({ title, kind, records, update }: { title: string; kind: "experience" | "internships" | "campus" | "projects"; records: any[]; update: (fn: (d: Resume) => void) => void }) { return <section><div className="heading"><h1>{title}</h1><button className="secondary" onClick={() => update((d) => { if (kind === "projects") d.projects.push({ name: "", role: "", date: "", bullets: [] }); else (d as any)[kind].push({ organization: "", role: "", date: "", bullets: [] }); })}>添加{title}</button></div>{records.map((item, index) => <div className="card" key={index}><div className="fields three"><label><span>{kind === "projects" ? "项目名称" : "单位"}</span><input value={kind === "projects" ? item.name : item.organization} onChange={(e) => update((d) => { if (kind === "projects") d.projects[index].name = e.target.value; else (d as any)[kind][index].organization = e.target.value; })} /></label><label><span>角色</span><input value={item.role} onChange={(e) => update((d) => { (d as any)[kind][index].role = e.target.value; })} /></label><label><span>时间</span><input value={item.date} onChange={(e) => update((d) => { (d as any)[kind][index].date = e.target.value; })} /></label></div><label><span>内容要点（每行一条）</span><textarea value={item.bullets.join("\n")} onChange={(e) => update((d) => { (d as any)[kind][index].bullets = e.target.value.split("\n"); })} /></label><button className="danger" onClick={() => update((d) => { (d as any)[kind].splice(index, 1); })}>删除</button></div>)}</section>; }
function Lines({ title, values, update }: { title: string; values: string[]; update: (v: string[]) => void }) { return <section><h1>{title}</h1><label><span>每行一项</span><textarea className="large" value={values.join("\n")} onChange={(e) => update(e.target.value.split("\n"))} /></label></section>; }
function Custom({ resume, update }: { resume: Resume; update: (fn: (d: Resume) => void) => void }) { return <section><h1>自定义模块</h1>{resume.customSections.map((item, index) => <div className="card" key={item.id}><label><span>模块 {index + 1} 标题</span><input value={item.title} onChange={(e) => update((d) => { d.customSections[index].title = e.target.value; })} /></label><label><span>内容（每行一条）</span><textarea value={item.lines.join("\n")} onChange={(e) => update((d) => { d.customSections[index].lines = e.target.value.split("\n"); })} /></label></div>)}</section>; }

function Preview({ resume }: { resume: Resume }) { const baseClass = `paper paper-${resume.fontSize} spacing-${resume.spacing}`; return <article className={baseClass}><h1>{text(resume.profile.name)}</h1><p className="meta">{[resume.profile.headline, resume.targetRole, resume.profile.city, resume.profile.phone, resume.profile.email].map(text).filter(Boolean).join(" · ")}</p>{resume.sectionOrder.map((id) => <PreviewSection key={id} id={id} resume={resume} />)}</article>; }
function PreviewSection({ id, resume }: { id: SectionId; resume: Resume }) { if (id === "summary") return text(resume.summary) ? <PaperSection title="个人概述"><p>{text(resume.summary)}</p></PaperSection> : null; if (id === "education") { const values = resume.education.filter((x) => Object.values(x).some(text)); return values.length ? <PaperSection title="教育经历">{values.map((x, i) => <div className="row" key={i}><strong>{[x.school, x.major, x.degree].map(text).filter(Boolean).join(" · ")}</strong><time>{text(x.date)}</time></div>)}</PaperSection> : null; } if (id === "awards" || id === "skills") { const values = (id === "awards" ? resume.awards : resume.skills).map(text).filter(Boolean); return values.length ? <PaperSection title={sectionLabels[id]}><ul>{values.map((x, i) => <li key={i}>{x}</li>)}</ul></PaperSection> : null; } if (id.startsWith("custom")) { const item = resume.customSections.find((x) => x.id === id); return item && text(item.title) && item.lines.map(text).filter(Boolean).length ? <PaperSection title={text(item.title)}><ul>{item.lines.map(text).filter(Boolean).map((x, i) => <li key={i}>{x}</li>)}</ul></PaperSection> : null; } const values = resume[id as "experience" | "internships" | "campus" | "projects"] as Resume["experience"] | Resume["projects"]; const visible = values.filter((x) => Object.values(x).some((v) => Array.isArray(v) ? v.some(text) : text(v))); return visible.length ? <PaperSection title={sectionLabels[id]}>{visible.map((x, i) => <div className="item" key={i}><div className="row"><strong>{["name" in x ? x.name : x.organization, x.role].map(text).filter(Boolean).join(" · ")}</strong><time>{text(x.date)}</time></div>{x.bullets.map(text).filter(Boolean).length ? <ul>{x.bullets.map(text).filter(Boolean).map((b, j) => <li key={j}>{b}</li>)}</ul> : null}</div>)}</PaperSection> : null; }
function PaperSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="paper-section"><h2>{title}</h2>{children}</section>; }
